server {
    listen 80;
    server_name ron.x52.uk;

    root /usr/share/nginx/html;
    index index.html;
    
    location ~* \.(png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
